-- 코드를 입력하세요
SELECT
    BB.WRITER_ID,
    U.NICKNAME,
    BB.TOTAL_SALES
FROM
    (SELECT 
        DISTINCT(B.WRITER_ID) AS WRITER_ID, 
        SUM(B.PRICE) AS TOTAL_SALES
    FROM
        USED_GOODS_BOARD AS B
    WHERE 
        B.STATUS = 'DONE'
    GROUP 
        BY B.WRITER_ID
    ) AS BB
    LEFT JOIN USED_GOODS_USER AS U
    ON BB.WRITER_ID = U.USER_ID
    
WHERE BB.TOTAL_SALES >= 700000
ORDER BY BB.TOTAL_SALES ASC