-- 코드를 입력하세요
SELECT
    DISTINCT(DATE_FORMAT(A.DATETIME, '%H')) AS 'HOUR'
    , COUNT(DATE_FORMAT(A.DATETIME, '%H')) AS 'COUNT'
FROM
    ANIMAL_OUTS AS A
WHERE DATE_FORMAT(A.DATETIME, '%H') BETWEEN 9 AND 20
GROUP BY DATE_FORMAT(A.DATETIME, '%H')
ORDER BY DATE_FORMAT(A.DATETIME, '%H') ASC