-- 코드를 입력하세요
SELECT
    B.BOOK_ID,
    DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS B
WHERE B.CATEGORY = '인문'
AND DATE_FORMAT(B.PUBLISHED_DATE, '%Y') = '2021'
ORDER BY PUBLISHED_DATE ASC