-- 코드를 입력하세요
SELECT
    F.INGREDIENT_TYPE AS INGREDIENT_TYPE,
    SUM(H.TOTAL_ORDER) AS TOTAL_ORDER
FROM
    ICECREAM_INFO AS F
    LEFT JOIN FIRST_HALF AS H
    ON F.FLAVOR = H.FLAVOR
GROUP BY F.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC