SELECT 
    B.BOOK_ID AS BOOK_ID,
    -- B.CATEGORY AS CATEGORY,
    A.AUTHOR_NAME AS AUTHOR_NAME,
    DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM
    BOOK AS B
    LEFT JOIN AUTHOR AS A
    ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE ASC

